Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("digite um nuemro: ")
leia(num)

se num mod 2 = 0  entao
   escreva("O numero: ",num,"é par")
senao
   escreva("O numero: ",num,"é impar")

fimse

Fimalgoritmo