Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
anosD,idade,dias : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
anosD <- 360

escreva("Digite sua idade: ")
leia(idade)

dias <- anosD * idade
escreva("Você viveu ",dias," dias na sua vida")


Fimalgoritmo