Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
numA,numB : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("digite o primeiro numero: ")
leia(numA)

escreva("digite o segundo numero: ")
leia(numB)

escreva("os numeros digitados foram: ",numB,numA)

Fimalgoritmo