Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
temperatura : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite o valor da temperatura ambiente: ")
leia (temperatura)

se temperatura >= 25 entao
escreva("esta muito quente")
senao
escreva("a temperatura esta agradavel")
fimse

Fimalgoritmo