Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis

numero: vetor[0..99] de inteiro
i: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i <-0 ate 99 faca
escreval("Digite o numero de matricula do aluno: ",i+1)
leia(numero[i])
fimpara


Fimalgoritmo