Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
// Seção de Declarações das variáveis 
num,num2 : vetor[0..50] de real
i : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i <- 0 ate 50 faca
  escreval("digite o ",i+1," numero")
  leia(num[i])
   num2[i]<-num[i]*3
   escreval("o numero vezes 3 é: ", num2[i])
fimpara





Fimalgoritmo